name: First Action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Working Directory
        run: pwd
      - name: Print Greeting
        run: echo "deployment"
      - name: Print goodbye
        run: echo "Good bye"
