name: OUTPUT INFORMATION
on: [push, workflow_dispatch]
jobs:
  info:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: second-action-react
    steps:
      - name: OUTPUT Github context
        run: echo "${{ github }}"
