name: Deploy react website
on: workflow_dispatch
jobs:
  gather-dependencies:
    runs-on: ubuntu-latest
      steps:
        - name:  install dependences
          run: cd expendicutre
        - name: run test
          run: npm run test
        - name: deploy
          run: npm run deploy
