name: Deploy a static website
on: workflow_dispatch
jobs:
  Gather-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm ci
      - name: Integration test
        run: npm run test
      - name: Deploy
        run: npm run build
