name: Test Project
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: output the current directory
        run: tree .
      - name: Install Dependencies
        working-directory: second-action-react
        run: npm ci
      - name: Run Tests
        working-directory: second-action-react
        run: npm run test
